добавить отзывы в filmorate
koka77/java-filmorate pull request #12
Opened 2022-07-01 03:38 UTC by Lusiolla

Добавлены отзывы

2022-07-01 08:52 UTC, koka77 requested changes

2022-07-01 08:52 UTC, koka77 commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    ReviewService service;
поле должно быть приватным и желательно финал

2022-07-01 08:52 UTC, koka77 commented on src/main/java/ru/yandex/practicum/filmorate/service/review/ReviewServiceIml.java
> +public class ReviewServiceIml implements ReviewService {
опечатка Iml - Impl

2022-07-01 08:52 UTC, koka77 commented on src/main/java/ru/yandex/practicum/filmorate/service/review/ReviewServiceIml.java
> +    ReviewStorage reviewStorage;
поля должны быть приватными и желательно финальными

2022-07-01 08:52 UTC, koka77 commented on src/main/java/ru/yandex/practicum/filmorate/storage/jdbc/impl/ReviewDaoImpl.java
> +    JdbcTemplate jdbcTemplate;
приват финал

2022-07-01 08:52 UTC, koka77 commented on src/main/java/ru/yandex/practicum/filmorate/storage/jdbc/impl/ReviewDaoImpl.java
> +    public void deleteLikeOrDislike(long reviewId, long userId, boolean isLike) {
Возможно стоит разбить на 2 метода

2022-07-01 08:52 UTC, koka77 commented on src/main/java/ru/yandex/practicum/filmorate/storage/jdbc/impl/ReviewDaoImpl.java
> +    public Collection<Review> findAllByIdFilm(Long filmId, int count) {
Точно нужно разбить на 2 метода

2022-07-01 08:52 UTC, koka77 commented on src/main/java/ru/yandex/practicum/filmorate/storage/jdbc/impl/ReviewDaoImpl.java
> +    public void insertLikeOrDislike(long reviewId, long userId, boolean isLike) {
Возможно стоит разбить на 2 метода

2022-07-01 08:52 UTC, koka77 commented on src/main/java/ru/yandex/practicum/filmorate/exception/NoUserException.java
> -package ru.yandex.practicum.filmorate.exception;
Не могу понять, это пустой файл?

2022-07-01 15:19 UTC, Lusiolla commented on src/main/java/ru/yandex/practicum/filmorate/service/review/ReviewServiceIml.java
> +    ReviewStorage reviewStorage;
вечно забываю! принято

2022-07-01 15:21 UTC, Lusiolla commented on src/main/java/ru/yandex/practicum/filmorate/storage/jdbc/impl/ReviewDaoImpl.java
> +    public void deleteLikeOrDislike(long reviewId, long userId, boolean isLike) {
Принято

2022-07-01 15:22 UTC, Lusiolla commented on src/main/java/ru/yandex/practicum/filmorate/exception/NoUserException.java
> -package ru.yandex.practicum.filmorate.exception;
Хм, посмотрю

2022-07-01 21:09 UTC, Zoohel commented on src/main/java/ru/yandex/practicum/filmorate/storage/jdbc/impl/ReviewDaoImpl.java
> +    public Optional<Review> findById(long id) {
Реализация метода findById в ReviewDaoImpl может быть оптимизирована до:
...
if (rs.next()) {
return Optional.of(makeReview(rs));
} else {
...

2022-07-01 21:09 UTC, Zoohel commented on src/main/java/ru/yandex/practicum/filmorate/storage/jdbc/impl/ReviewDaoImpl.java
> +        SqlRowSet rsFilm = jdbcTemplate.queryForRowSet("select film_id from films where film_id = ?",
SQL собран в константах класса, этот запрос тоже можно разместить там, будет удобнее читать и сопровождать код

2022-07-01 21:09 UTC, Zoohel commented on src/main/java/ru/yandex/practicum/filmorate/storage/jdbc/impl/ReviewDaoImpl.java
> +        SqlRowSet rsUser = jdbcTemplate.queryForRowSet("select user_id from users where user_id = ?",
SQL собран в константах класса, этот запрос тоже можно разместить там, будет удобнее читать и сопровождать код

2022-07-01 21:11 UTC, Zoohel commented
Классный код, лаконичный и понятный, хорошая работа

2022-07-02 18:01 UTC, Zoohel approved these changes
Супер!

2022-07-04 11:49 UTC, merged